const mongoose = require("mongoose");

// One document per conversation. The conversationId is generated by the
// frontend once per chat session (see NirantarAiChat.jsx) and is completely
// independent of whichever AI provider handles any given message — that
// independence is what lets a conversation survive a cloud->Ollama fallback
// mid-stream without looking like a new/unrelated chat to the student.
const messageSchema = new mongoose.Schema(
  {
    role: { type: String, enum: ["user", "assistant"], required: true },
    content: { type: String, required: true },
    // Provider/model metadata is for backend logging/debugging only — never
    // sent to the AI as part of the conversational context, and the
    // frontend chat bubble doesn't render it either.
    provider: { type: String, enum: ["cloud", "ollama"] },
    model: { type: String },
  },
  { timestamps: { createdAt: true, updatedAt: false }, _id: false }
);

const conversationSchema = new mongoose.Schema(
  {
    conversationId: { type: String, required: true, unique: true, index: true },
    school: { type: mongoose.Schema.Types.ObjectId, ref: "School", required: true },
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    // "student" or "teacher" — kept only so an admin/debug view could tell
    // conversations apart; access control itself is by `user`, not this.
    namespace: { type: String },
  },
  { timestamps: true }
);
conversationSchema.add({ messages: [messageSchema] });

module.exports = mongoose.model("Conversation", conversationSchema);
